- name: Create Resources Folder
  file:
    path: "{{ docker_folder }}"
    state: directory

- name: Clone
  git:
    repo: "http://{{ username }}:{{ password }}@54.183.118.41:djcrucena/tomcat.git"
    dest: "{{ docker_folder }}"

- name: Download war file
  get_url:
    url: http://http://52.9.11.105/nexus/content/repositories/snapshots/DTSActivity/CurrencyConverter/1/CurrencyConverter-1.war
    dest: "{{ docker_folder }}/Resources/CurrencyConverter-1.war"
    mode: 0644
    url_password: "{{ password }}"
    url_username: "{{ username }}"

- name: Check
  shell: "pwd && ls -lart && whoami"
  register: output
  
- name: Display
  debug: var=output
